import ChatCard from "./ChatCard";
import { Button } from "@/components/ui/button";
import { SendHorizontal } from "lucide-react";
import { Textarea } from "@/components/ui/textarea";

const chatData = [
  {
    content: "What is the average temperature in the earth's mantle?",
    sender: "user",
  },
  {
    content:
      "The average temperature in Earth's mantle varies depending on depth. The Earth's mantle is divided into several layers, and each layer has a different temperature profile. However, on average, the temperature in the uppermost part of the mantle, which is closest to the Earth's crust, is around 900 to 1,300 degrees Celsius (1,652 to 2,372 degrees Fahrenheit). As you go deeper into the mantle, the temperature increases due to the heat generated by the natural radioactive decay of elements and the residual heat from the planet's formation. In the lower mantle, temperatures can exceed 2,000 degrees Celsius (3,632 degrees Fahrenheit).",
    sender: "ai",
  },
  {
    content: "Tell me a random fun fact about the Roman Empire",
    sender: "user",
  },
  {
    content:
      "Sure, here's a random fun fact about the Roman Empire: The Romans used a condiment called 'garum' in their cuisine, which was made by fermenting fish in salt. Garum was a popular and pungent fish sauce that was used to season many",
    sender: "ai",
  },
];

const alignChat = (sender: string) => {
  if (sender === "user") return "self-end";
  return "self-start";
};

const ChatField = () => {
  return (
    <div className="w-full max-h-[80vh] max-w-screen-lg flex flex-col justify-between gap-6">
      <div className="flex flex-col gap-3 overflow-y-scroll p-4 shadow-md dark:shadow-slate-800 rounded-lg">
        {chatData.map(({ content, sender }, index) => (
          <div key={index} className={alignChat(sender)}>
            <ChatCard content={content} sender={sender} />
          </div>
        ))}
      </div>
      <div className="flex gap-2 items-center">
        <Textarea placeholder="Enter your message..." className="resize-none" />
        <Button>
          <SendHorizontal />
        </Button>
      </div>
    </div>
  );
};

export default ChatField;
